env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: [
  {
    files: [src/render.js, src/controllers.js],
    rules: {
      no-param-reassign: warn
    }
  }
]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
