env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: [
  {
    files: src/render.js,
    rules: {
      no-param-reassign: warn
    }
  }
]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
